name: terraform deployment
on: workflow_dispatch
jobs:
  terraform-configure:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install terraform
        uses: 
